# Generated by Django 4.2.7 on 2023-12-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0002_news_body_alter_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='newsid',
            field=models.ManyToManyField(to='newsApp.news'),
        ),
    ]
