# Generated by Django 4.2.7 on 2023-12-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0003_topic_newsid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='newsid',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news',
        ),
        migrations.AddField(
            model_name='news',
            name='news',
            field=models.ManyToManyField(related_name='news', to='newsApp.topic'),
        ),
    ]
