# Generated by Django 4.2.7 on 2023-12-01 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0004_remove_topic_newsid_remove_news_news_news_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news',
            new_name='topic',
        ),
    ]
