# Generated by Django 4.2.7 on 2023-12-01 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0005_rename_news_news_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='topic',
            new_name='topics',
        ),
    ]
